jobs:
  lint:
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_DEFAULT_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    runs-on: self-host
    steps:
      - uses: actions/checkout@v1
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.24
      - run: terraform fmt -check -recursive
      - run: terraform init
      - run: terraform validate
name: Format and validate
"on":
  pull_request:
